org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.17.3
fabric_version=0.141.4+1.21.11

mod_version=0.1.0-beta1
maven_group=jp.maikurakobo
archives_base_name=maikura-inventory-expansion-fabric-mc1.21.11-v0.1.0-beta1

modmenu_version=17.0.0
